baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'bbuild'
theme = 'PaperMod'

[params]
  [params.profileMode]
    enabled = true
    title = "Hi, I'm Ben 👋"
    subtitle = "I am a software engineer who likes to build things and solve problems."
    imageUrl = "images/me.jpg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"
    
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts/"
    
    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/b97en"